Localization - Main module
SceptreOfficial/Simplex-Support-Services pull request #49
Opened 2020-08-16 21:53 UTC by Mysteryjuju

Add localization for Main module
Add french translation for Main module

2020-08-17 09:55 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Les admins seront capable d'utiliser tous les supports disponibles</French>
Les admins pourront utiliser tous les supports disponibles

2020-08-17 09:57 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Limiter l'accès admin à la faction</French>
Faction renvoie peut-être à un type d'unités (ex. talibans, rebelles, US marines, etc.) ? Peut-être utiliser simplement le mot "camp"

2020-08-17 09:59 UTC, Tanin69 commented on addons/main/stringtable.xml
> +		</Key>
Supprime (typo)

2020-08-17 10:02 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Fournir un terminal pour les requêtes de drone</French>
Cohérence : tout à l'infinitif ou tout conjugué : fournit ou fournir. La version anglaise n'est pas cohérente non plus (give : infinitif ou gives, conjugué) -> préférer peut-être l'infinitif car moins de corrections à faire sur la version anglaise.

2020-08-17 10:05 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Les admins seront capable d'utiliser tous les supports disponibles</French>
Cohérence : tout mettre à l'infinitif (donc présent) plutôt que conjugué au futur (ou au présent dans certains cas). La version anglaise n'est pas non plus cohérente.

2020-08-17 10:12 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<English>Give admins access to all supports</English>
Sauf erreur de ma part, il s'agit de l'admin serveur Arma connecté. Donc, il ne peut y en avoir qu'un.

2020-08-17 10:14 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Fournir un terminal pour les requêtes de drone</French>
Détail : il me semble qu'il faut plutôt traduire "request" par "demande" dans ce contexte.

2020-08-17 10:16 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Fournit un terminal de controle s'il n'en possède pas au joueur capable de faire des requêtes de drone</French>
"Fournir un terminal de contrôle au demandeur d'appui aérien rapproché s'il n'en possède pas"

2020-08-17 10:17 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<English>When disabled, anyone can interact directly with transports or logistics booths</English>
When disabled, allow anyone to interact directly with transports or logistics booths

2020-08-17 10:17 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Si désactivé, tout le monde est capable d'interagir directement avec les transports ou les containers de logistique</French>
Si désactivé, autoriser tout le monde à interagir directement avec les transports ou les containers de logistique

2020-08-17 10:20 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<English>If disabled, any physical support vehicles capable of respawning will simply respawn</English>
If disabled, allow any physical support vehicles to respawn if capable

2020-08-17 10:21 UTC, Tanin69 commented on addons/main/stringtable.xml
> +		</Key>
Si désactivé, autoriser tout véhicule de support à réapparaître s'il en est capable

2020-08-17 10:23 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<English>When a support entity is deleted/removed, its physical vehicle will be deleted</English>
Delete physical vehicle when the corresponding support entity is deleted/removed

2020-08-17 10:24 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Quand une entité de support est supprimée, son véhicule le sera aussi</French>
Supprimer le véhicule physique lorsque l'entité de support est supprimée ou retirée

2020-08-17 10:28 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Supprime l'équipage si le véhicule respawn</French>
Supprimer l'équipage précédent si le véhicule réapparaît

2020-08-17 10:43 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Utiliser le chat pour les notifications</French>
Moi, je préfère la souris

2020-08-17 15:05 UTC, Tanin69 commented on addons/main/stringtable.xml
> +			<French>Limite les accès admin aux supports de la faction de l'admin</French>
French translation : consistency : using infinitive form everywhere would be better for display name 

Example :
<English>Allow admin to use every support available</English>
<French>Permettre à l'admin d'utiliser tous les supports disponibles</French>

2020-08-18 07:11 UTC, SceptreOfficial commented on addons/main/stringtable.xml
> +		<Key ID="STR_SSS_Main_SimplexSupportService">
This key needs the "s" at the end for it to be more accurate of the title.
`"STR_SSS_Main_SimplexSupportService"` --> `"STR_SSS_Main_SimplexSupportServices"`

2020-08-18 07:13 UTC, SceptreOfficial commented on addons/main/stringtable.xml
> +		<Key ID="STR_SSS_Main_SimplexSupportService">
This key needs the "s" at the end for it to be more accurate of the title.
`"STR_SSS_Main_SimplexSupportService"` --> `"STR_SSS_Main_SimplexSupportServices"`

2020-08-21 08:01 UTC, la-Vieille commented on addons/main/stringtable.xml
> +			<French>Fournit un terminal de controle s'il n'en possède pas au joueur capable de faire des demandes de drone.</French>
proposition : 
« Fournit, si le joueur n'en possède pas, un terminal de contrôle pour les demandes de drones.  »

2020-08-21 08:03 UTC, la-Vieille commented on addons/main/stringtable.xml
> +			<French>Si activé, les véhicules détruits ne réapparaîtront pas, même s'ils sont configurés pour.</French>
correction : 
« **A**ctivé […] >

2020-08-21 08:04 UTC, la-Vieille commented on addons/main/stringtable.xml
> +			<French>L'équipage sera supprimé lorsque le véhicule ne sera plus utilisable.</French>
Proposition : 
« L'équipage est supprimé si le véhicule n'est plus utilisable. »

2020-08-25 08:53 UTC, Mysteryjuju commented
There is just a missing text in script_macros.hpp not localized.

2020-08-25 19:56 UTC, Elgin675 requested changes

2020-08-25 19:56 UTC, Elgin675 commented on addons/main/stringtable.xml
> +			<French>Liste du matériel héliportable</French>
```suggestion
			<French>Liste blanche du matériel héliportable</French>
```

2020-08-25 19:56 UTC, Elgin675 commented on addons/main/stringtable.xml
> +			<French>Limite le matériel héliportable à ces seuls classnames.</French>
```suggestion
			<French>Limite le matériel héliportable à ces seuls classnames.\nLaisser le champ vide pour permettre le transport de tous les équipements héliportables.</French>
```

2020-08-25 19:56 UTC, Elgin675 commented on addons/main/stringtable.xml
> +			<French>Rayon de la zone de collecte du matériel héliportable</French>
```suggestion
			<French>Zone de recherche du matériel héliportable</French>
```

2020-08-25 19:56 UTC, Elgin675 commented on addons/main/stringtable.xml
> +			<French>Définit le rayon de la zone de collecte où doit se trouver le matériel héliportable.</French>
```suggestion
			<French>Définit le rayon, en mètres, au-delà duquel l'hélicoptère ne sera plus en mesure de trouver du matériel à transporter.</French>
```

2020-08-26 03:46 UTC, SceptreOfficial commented
> There is just a missing text in script_macros.hpp not localized.

If you want to add these entries and some translations to the stringtable before I merge, I can modify script_macros.hpp.

```
<Key ID="STR_SSS_Main_NotReady">
	<English>NOT READY.</English>
</Key>
<Key ID="STR_SSS_Main_ReadyIn">
	<English>Ready in</English>
</Key>
<Key ID="STR_SSS_Main_BeQuiet">
	<English>We'll be quiet.</English>
</Key>
```

2020-08-26 08:53 UTC, Mysteryjuju commented
As you want. I don't have access to my gaming PC until end of the week, so I can't test my script update now.

2020-09-01 02:40 UTC, merged